<?php

declare(strict_types=1);

namespace App\Domain\Value;

/**
 * Represents a preview of a flashcard generated by AI.
 *
 * This is NOT persisted to database - it's only used for API responses
 * before the user saves the flashcard set.
 *
 * Enforces business rules:
 * - Front and back cannot be empty
 * - Maximum 1000 characters each (mirrors DB constraint)
 */
final readonly class CardPreview
{
    private const MAX_LENGTH = 1000;

    private function __construct(
        public string $front,
        public string $back,
    ) {
        $this->validateSide('front', $this->front);
        $this->validateSide('back', $this->back);
    }

    public static function create(string $front, string $back): self
    {
        return new self($front, $back);
    }

    public function toArray(): array
    {
        return [
            'front' => $this->front,
            'back' => $this->back,
        ];
    }

    private function validateSide(string $sideName, string $value): void
    {
        $trimmed = trim($value);

        if ('' === $trimmed) {
            throw new \InvalidArgumentException(sprintf('Card %s cannot be empty', $sideName));
        }

        $length = mb_strlen($trimmed, 'UTF-8');

        if ($length > self::MAX_LENGTH) {
            throw new \InvalidArgumentException(sprintf('Card %s must not exceed %d characters, got %d', $sideName, self::MAX_LENGTH, $length));
        }
    }
}
