<?php

declare(strict_types=1);

namespace App\Domain\Value;

/**
 * Represents a suggested name for a flashcard set generated by AI.
 *
 * This is a lighter version of SetName - it's only a suggestion
 * that the user can accept or modify before saving.
 *
 * Enforces business rules:
 * - Cannot be empty
 * - Maximum 255 characters (mirrors DB constraint)
 */
final readonly class SuggestedSetName
{
    private const MAX_LENGTH = 255;

    private function __construct(
        public string $value,
    ) {
        $this->validate($value);
    }

    public static function fromString(string $name): self
    {
        return new self($name);
    }

    public function toString(): string
    {
        return $this->value;
    }

    private function validate(string $name): void
    {
        $trimmed = trim($name);

        if ('' === $trimmed) {
            throw new \InvalidArgumentException('Suggested set name cannot be empty');
        }

        $length = mb_strlen($trimmed, 'UTF-8');

        if ($length > self::MAX_LENGTH) {
            throw new \InvalidArgumentException(sprintf('Suggested set name must not exceed %d characters, got %d', self::MAX_LENGTH, $length));
        }
    }
}
