<?php

declare(strict_types=1);

namespace App\Domain\Model;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * AI Job entity - tracks AI flashcard generation requests
 *
 * Lifecycle: queued -> running -> succeeded|failed
 * Stores preview cards in JSONB before user saves them as a Set
 */
#[ORM\Entity]
#[ORM\Table(name: 'ai_jobs')]
#[ORM\Index(name: 'ai_jobs_user_time', columns: ['user_id', 'created_at'])]
#[ORM\Index(name: 'ai_jobs_status_time', columns: ['status', 'created_at'])]
#[ORM\Index(name: 'ai_jobs_set', columns: ['set_id'])]
class AiJob
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    private Uuid $id;

    #[ORM\Column(type: 'uuid')]
    private Uuid $userId;

    #[ORM\Column(type: 'uuid', nullable: true)]
    private ?Uuid $setId = null;

    /**
     * Job status: queued, running, succeeded, failed
     * Maps to PostgreSQL ENUM ai_job_status
     */
    #[ORM\Column(type: 'string', length: 20, enumType: AiJobStatus::class)]
    private AiJobStatus $status;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $errorMessage = null;

    /**
     * User's input text (1000-10000 chars per PRD)
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $requestPrompt = null;

    /**
     * Preview cards stored as JSONB array before user saves
     * Structure: [{ tmp_id: uuid, front: string, back: string, edited: bool, deleted: bool }]
     */
    #[ORM\Column(type: Types::JSON)]
    private array $cards = [];

    /**
     * Number of cards generated by AI (right after completion)
     */
    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $generatedCount = 0;

    /**
     * Count of cards edited by user in preview
     */
    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $editedCount = 0;

    /**
     * Count of cards marked as deleted in preview
     */
    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $deletedCount = 0;

    /**
     * AI-suggested name for the set
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $suggestedName = null;

    /**
     * Raw JSON response from AI API (OpenRouter.ai)
     */
    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $responseRaw = null;

    /**
     * AI model used (e.g., "gpt-4", "claude-3")
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $modelName = null;

    /**
     * Input tokens (for cost tracking)
     */
    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $tokensIn = null;

    /**
     * Output tokens (for cost tracking)
     */
    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $tokensOut = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $updatedAt;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $completedAt = null;

    public function __construct()
    {
        $this->id = Uuid::v4();
        $this->status = AiJobStatus::QUEUED;
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getUserId(): Uuid
    {
        return $this->userId;
    }

    public function setUserId(Uuid $userId): self
    {
        $this->userId = $userId;
        return $this;
    }

    public function getSetId(): ?Uuid
    {
        return $this->setId;
    }

    public function setSetId(?Uuid $setId): self
    {
        $this->setId = $setId;
        return $this;
    }

    public function getStatus(): AiJobStatus
    {
        return $this->status;
    }

    public function setStatus(AiJobStatus $status): self
    {
        $this->status = $status;
        $this->updatedAt = new \DateTimeImmutable();
        return $this;
    }

    public function getErrorMessage(): ?string
    {
        return $this->errorMessage;
    }

    public function setErrorMessage(?string $errorMessage): self
    {
        $this->errorMessage = $errorMessage;
        return $this;
    }

    public function getRequestPrompt(): ?string
    {
        return $this->requestPrompt;
    }

    public function setRequestPrompt(?string $requestPrompt): self
    {
        $this->requestPrompt = $requestPrompt;
        return $this;
    }

    public function getCards(): array
    {
        return $this->cards;
    }

    public function setCards(array $cards): self
    {
        $this->cards = $cards;
        $this->updatedAt = new \DateTimeImmutable();
        return $this;
    }

    public function getGeneratedCount(): int
    {
        return $this->generatedCount;
    }

    public function setGeneratedCount(int $generatedCount): self
    {
        $this->generatedCount = $generatedCount;
        return $this;
    }

    public function getEditedCount(): int
    {
        return $this->editedCount;
    }

    public function setEditedCount(int $editedCount): self
    {
        $this->editedCount = $editedCount;
        return $this;
    }

    public function getDeletedCount(): int
    {
        return $this->deletedCount;
    }

    public function setDeletedCount(int $deletedCount): self
    {
        $this->deletedCount = $deletedCount;
        return $this;
    }

    public function getSuggestedName(): ?string
    {
        return $this->suggestedName;
    }

    public function setSuggestedName(?string $suggestedName): self
    {
        $this->suggestedName = $suggestedName;
        return $this;
    }

    public function getResponseRaw(): ?array
    {
        return $this->responseRaw;
    }

    public function setResponseRaw(?array $responseRaw): self
    {
        $this->responseRaw = $responseRaw;
        return $this;
    }

    public function getModelName(): ?string
    {
        return $this->modelName;
    }

    public function setModelName(?string $modelName): self
    {
        $this->modelName = $modelName;
        return $this;
    }

    public function getTokensIn(): ?int
    {
        return $this->tokensIn;
    }

    public function setTokensIn(?int $tokensIn): self
    {
        $this->tokensIn = $tokensIn;
        return $this;
    }

    public function getTokensOut(): ?int
    {
        return $this->tokensOut;
    }

    public function setTokensOut(?int $tokensOut): self
    {
        $this->tokensOut = $tokensOut;
        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function getCompletedAt(): ?\DateTimeImmutable
    {
        return $this->completedAt;
    }

    public function setCompletedAt(?\DateTimeImmutable $completedAt): self
    {
        $this->completedAt = $completedAt;
        return $this;
    }

    /**
     * Mark job as completed and set completion timestamp
     */
    public function markCompleted(): self
    {
        $this->completedAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
        return $this;
    }

    /**
     * Check if job is in terminal state (succeeded or failed)
     */
    public function isCompleted(): bool
    {
        return $this->status->isTerminal();
    }

    /**
     * Calculate kept cards count (generated - deleted)
     */
    public function getKeptCount(): int
    {
        return $this->generatedCount - $this->deletedCount;
    }
}