<?php

declare(strict_types=1);

namespace App\Infrastructure\Integration\OpenRouter\DTO;

use InvalidArgumentException;

/**
 * Represents a single flashcard generated by AI.
 * Immutable DTO with validated front and back content.
 */
final readonly class Flashcard
{
    public function __construct(
        public string $front,
        public string $back,
    ) {
        // Validate non-empty content
        if (trim($this->front) === '') {
            throw new InvalidArgumentException('Flashcard front cannot be empty');
        }

        if (trim($this->back) === '') {
            throw new InvalidArgumentException('Flashcard back cannot be empty');
        }
    }

    /**
     * Factory method to create Flashcard from array.
     *
     * @param array{front: string, back: string} $data
     * @throws InvalidArgumentException If data structure is invalid
     */
    public static function fromArray(array $data): self
    {
        if (!isset($data['front'])) {
            throw new InvalidArgumentException('Missing required field: front');
        }

        if (!isset($data['back'])) {
            throw new InvalidArgumentException('Missing required field: back');
        }

        return new self(
            front: (string) $data['front'],
            back: (string) $data['back'],
        );
    }

    /**
     * Convert flashcard to array representation.
     *
     * @return array{front: string, back: string}
     */
    public function toArray(): array
    {
        return [
            'front' => $this->front,
            'back' => $this->back,
        ];
    }
}
