<?php

declare(strict_types=1);

namespace App\UI\Http\Controller;

use App\Domain\Repository\SetRepositoryInterface;
use App\Domain\Value\UserId;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * Controller for GET /sets route.
 *
 * Displays list of all user's flashcard sets with:
 * - Set name, card count, creation date
 * - Origin badge (AI/Manual)
 * - Actions: Learn, Edit, Delete
 */
#[Route('/sets', name: 'set_list', methods: ['GET'])]
#[IsGranted('ROLE_USER')]
final class SetListController extends AbstractController
{
    public function __construct(
        private readonly SetRepositoryInterface $setRepository,
    ) {
    }

    public function __invoke(): Response
    {

        // 1. Get current user ID
        $user = $this->getUser();

        if ($user === null) {
            return $this->json([
                'error' => 'Authentication required',
                'code' => 'unauthorized',
            ], Response::HTTP_UNAUTHORIZED);
        }

        $userId = $user->getId();

        $sets = $this->setRepository->findActiveOwnedBy($userId);

        // 3. Transform to view DTOs
        $setsData = array_map(function ($set) {
            // Check if set was AI-generated by looking at generatedAt field
            $isAiGenerated = false;
            try {
                // Use reflection to check private property (temporary solution)
                $reflection = new \ReflectionClass($set);
                $property = $reflection->getProperty('generatedAt');
                $property->setAccessible(true);
                $isAiGenerated = $property->getValue($set) !== null;
            } catch (\ReflectionException $e) {
                // Fallback: assume manual if reflection fails
                $isAiGenerated = false;
            }

            return [
                'id' => $set->getId(),
                'name' => $set->getName()->toString(),
                'card_count' => $set->getCardCount(),
                'created_at' => $set->getCreatedAt(),
                'is_ai_generated' => $isAiGenerated,
            ];
        }, $sets);

        // 4. Render template
        return $this->render('sets/list.html.twig', [
            'sets' => $setsData,
        ]);
    }
}
